name: syn2real
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - comm=0.1.2
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.2.128
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.2.128
  - cuda-nsight-compute=12.2.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.2.128
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.2.131
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.2.131
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.2.128
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cudatoolkit=11.6.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - freetype=2.10.4
  - gds-tools=1.7.1.12
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libclang=10.0.1
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.7.1.12
  - libcufile-dev=1.7.1.12
  - libcurand=10.3.3.129
  - libcurand-dev=10.3.3.129
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libllvm10=10.0.1
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.37
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nsight-compute=2023.2.1.3
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.10
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchvision=0.13.1
  - tornado=6.3.2
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - accelerate==0.21.0
      - addict==2.4.0
      - aliyun-python-sdk-core==2.13.36
      - aliyun-python-sdk-kms==2.16.1
      - altair==5.0.1
      - annotated-types==0.5.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - backports-zoneinfo==0.2.1
      - blinker==1.6.2
      - blis==0.7.10
      - braceexpand==0.1.7
      - cachetools==5.3.1
      - catalogue==2.0.9
      - cfgv==3.4.0
      - click==8.1.6
      - cmake==3.27.2
      - colorama==0.4.6
      - confection==0.1.1
      - contexttimer==0.3.3
      - contourpy==1.1.0
      - crcmod==1.7
      - cryptography==41.0.3
      - cycler==0.11.0
      - cymem==2.0.7
      - decord==0.6.0
      - diffusers==0.19.3
      - distlib==0.3.7
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - fairscale==0.4.4
      - filelock==3.12.2
      - fonttools==4.42.0
      - fsspec==2023.6.0
      - ftfy==6.1.1
      - gdown==4.7.1
      - gitdb==4.0.10
      - gitpython==3.1.32
      - huggingface-hub==0.16.4
      - identify==2.5.26
      - imageio==2.31.1
      - importlib-metadata==6.8.0
      - iopath==0.1.10
      - jmespath==0.10.0
      - kaggle==1.5.16
      - kiwisolver==1.4.4
      - langcodes==3.3.0
      - lazy-loader==0.3
      - lit==16.0.6
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - mmcls==0.25.0
      - mmcv-full==1.6.0
      - mmsegmentation==0.27.0
      - model-index==0.1.11
      - murmurhash==1.0.9
      - networkx==3.1
      - ninja==1.11.1
      - nodeenv==1.8.0
      - omegaconf==2.3.0
      - opencv-python==4.8.0.76
      - opencv-python-headless==4.5.5.64
      - opendatalab==0.0.10
      - opendatasets==0.1.22
      - openmim==0.3.9
      - openxlab==0.0.19
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==23.1
      - pandas==2.0.3
      - pathtools==0.1.2
      - pathy==0.10.2
      - pillow==9.5.0
      - plotly==5.16.0
      - portalocker==2.7.0
      - pre-commit==3.3.3
      - preshed==3.0.8
      - prettytable==3.8.0
      - protobuf==4.24.0
      - pyarrow==12.0.1
      - pycocoevalcap==1.2
      - pycocotools==2.0.6
      - pycryptodome==3.18.0
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pydeck==0.8.0
      - pympler==1.0.1
      - pyparsing==3.0.9
      - python-magic==0.4.27
      - python-slugify==8.0.1
      - pytorch-msssim==1.0.0
      - pytz==2023.3
      - pytz-deprecation-shim==0.1.0.post0
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.3.2
      - salesforce-lavis==1.0.2
      - scikit-image==0.21.0
      - scipy==1.10.1
      - sentencepiece==0.1.99
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - setuptools==60.2.0
      - smart-open==6.3.0
      - smmap==5.0.0
      - spacy==3.6.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.7
      - streamlit==1.25.0
      - tabulate==0.9.0
      - tenacity==8.2.2
      - terminaltables==3.1.10
      - text-unidecode==1.3
      - thinc==8.1.12
      - tifffile==2023.7.10
      - timm==0.4.12
      - tokenizers==0.13.3
      - toolz==0.12.0
      - torchshow==0.5.1
      - tqdm==4.65.2
      - transformers==4.26.1
      - typer==0.9.0
      - tzdata==2023.3
      - tzlocal==4.3.1
      - validators==0.21.2
      - virtualenv==20.24.3
      - wandb==0.15.9
      - wasabi==1.1.2
      - watchdog==3.0.0
      - webdataset==0.2.48
      - xformers==0.0.22+e153e4b.d20230829
      - yapf==0.40.1
      - zipp==3.16.2
